import { StyleSheet } from "react-native";
export const introStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  Box: {
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingBottom: 20,
  },
  header: {
    backgroundColor: '#3B82F6',
    paddingVertical: 24,
    marginBottom: 50,
    alignItems: 'center',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  main: {
    marginTop: 30,
  },
  mainOtp: {
    marginTop: 30,
    alignItems: 'center',
  },
  headerText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  label: {
    marginTop: 16,
    marginHorizontal: 16,
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  input: {
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#111827',
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  passwordInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 14,
    color: '#111827',
  },
  forgotPassword: {
    marginTop: 8,
    marginRight: 16,
    textAlign: 'right',
    fontSize: 12,
    color: '#6B7280',
  },
  signupText: {
    marginTop: 16,
    textAlign: 'center',
    fontSize: 12,
    color: '#374151',
  },
  signupLink: {
    color: '#2563EB',
    fontWeight: '600',
  },
  Button: {
    marginTop: 70,
    marginHorizontal: 16,
    backgroundColor: '#3B82F6',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 100,
  },
  ButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  instructionText: {
    fontSize: 16,
    color: '#1F2937',
    textAlign: 'center',
  },
  phoneText: {
    fontSize: 16,
    color: '#1F2937',
    fontWeight: '600',
    marginTop: 5,
    textAlign: 'center',
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    alignItems: 'center'
  },
  otpText: {
    fontSize: 20,
    color: '#1F2937',
  },
  numberPad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginTop: 30,
  },
  numberButton: {
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },
  numberText: {
    fontSize: 24,
    color: '#1F2937',
  },
  resendText: {
    marginTop: 20,
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
  signUpButton: {
    marginTop: 30,
    marginHorizontal: 16,
    backgroundColor: '#3B82F6',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    width: '90%',
  },
  signUpButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});